package com.restaurant.identity.application;

import com.restaurant.identity.infrastructure.*;
import com.restaurant.platform.api.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@Service
public class AccessManagementService {
 private static final Pattern EMAIL=Pattern.compile("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"); private static final Pattern EMPLOYEE=Pattern.compile("^[A-Z0-9][A-Z0-9_-]{2,31}$");
 private static final Map<String,Integer> RANK=Map.of("OWNER",100,"MANAGER",80,"SHIFT_MANAGER",60,"INVENTORY_MANAGER",50,"CASHIER",40,"WAITER",30,"KITCHEN",30);
 private static final Map<String,String[]> ROLE_PERMISSIONS=Map.of(
  "MANAGER",new String[]{"DASHBOARD_VIEW","ORDER_VIEW","ORDER_CREATE","ORDER_CANCEL","BILL_CREATE","PAYMENT_RECORD","DISCOUNT_APPLY","KOT_VIEW","KOT_UPDATE","MENU_VIEW","MENU_EDIT","PRICE_EDIT","FLOOR_VIEW","FLOOR_EDIT","STOCK_VIEW","STOCK_EDIT","STOCK_ADJUST","REPORT_OUTLET_VIEW","USER_VIEW","USER_MANAGE","BRANDING_OUTLET_EDIT","AUDIT_VIEW","SETTINGS_VIEW"},
  "SHIFT_MANAGER",new String[]{"DASHBOARD_VIEW","ORDER_VIEW","ORDER_CREATE","ORDER_CANCEL","BILL_CREATE","PAYMENT_RECORD","DISCOUNT_APPLY","KOT_VIEW","KOT_UPDATE","MENU_VIEW","FLOOR_VIEW","STOCK_VIEW","REPORT_OUTLET_VIEW"},
  "CASHIER",new String[]{"ORDER_VIEW","ORDER_CREATE","BILL_CREATE","PAYMENT_RECORD","DISCOUNT_APPLY","MENU_VIEW","FLOOR_VIEW"},
  "WAITER",new String[]{"ORDER_VIEW","ORDER_CREATE","MENU_VIEW","FLOOR_VIEW"},
  "KITCHEN",new String[]{"KOT_VIEW","KOT_UPDATE"},
  "INVENTORY_MANAGER",new String[]{"DASHBOARD_VIEW","MENU_VIEW","STOCK_VIEW","STOCK_EDIT","STOCK_ADJUST","REPORT_OUTLET_VIEW"});
 private static final String[][] PERMISSION_META={{"DASHBOARD_VIEW","View operational dashboard","OPERATIONS"},{"ORDER_VIEW","View orders","ORDERS"},{"ORDER_CREATE","Create orders","ORDERS"},{"ORDER_CANCEL","Cancel orders","ORDERS"},{"BILL_CREATE","Create bills","BILLING"},{"PAYMENT_RECORD","Record payments","BILLING"},{"DISCOUNT_APPLY","Apply permitted discounts","BILLING"},{"KOT_VIEW","View kitchen tickets","KITCHEN"},{"KOT_UPDATE","Update kitchen tickets","KITCHEN"},{"MENU_VIEW","View menu administration","MENU"},{"MENU_EDIT","Edit menu","MENU"},{"PRICE_EDIT","Edit prices","MENU"},{"FLOOR_VIEW","View floor and tables","FLOOR"},{"FLOOR_EDIT","Configure floor and tables","FLOOR"},{"STOCK_VIEW","View stock","INVENTORY"},{"STOCK_EDIT","Manage stock and recipes","INVENTORY"},{"STOCK_ADJUST","Adjust stock","INVENTORY"},{"REPORT_OUTLET_VIEW","View outlet reports","REPORTS"},{"REPORT_ALL_VIEW","View tenant-wide reports","REPORTS"},{"USER_VIEW","View staff and access","ADMIN"},{"USER_MANAGE","Create and assign staff","ADMIN"},{"BRANDING_OUTLET_EDIT","Edit outlet branding","ADMIN"},{"BRANDING_TENANT_EDIT","Edit tenant branding","ADMIN"},{"AUDIT_VIEW","View audit history","ADMIN"},{"SETTINGS_VIEW","View settings","ADMIN"}};
 private final UserRepository users; private final RoleRepository roles; private final UserRoleRepository userRoles; private final UserOutletRepository userOutlets; private final PermissionRepository permissions; private final RolePermissionRepository rolePermissions; private final PasswordEncoder encoder; private final AuditWriter audit; private final JdbcTemplate jdbc;
 public AccessManagementService(UserRepository u,RoleRepository r,UserRoleRepository ur,UserOutletRepository uo,PermissionRepository p,RolePermissionRepository rp,PasswordEncoder e,AuditWriter a,JdbcTemplate j){users=u;roles=r;userRoles=ur;userOutlets=uo;permissions=p;rolePermissions=rp;encoder=e;audit=a;jdbc=j;}

 @Transactional public Map<String,Object> catalog(){var p=admin();seed(p.tenantId());var allRoles=roles.findByTenantId(p.tenantId());var allPerms=permissions.findByTenantIdOrderByCategoryAscCodeAsc(p.tenantId());var mappings=rolePermissions.findByRoleIdIn(allRoles.stream().map(RoleEntity::getId).toList());Map<UUID,String> pc=allPerms.stream().collect(Collectors.toMap(PermissionEntity::getId,PermissionEntity::getCode));Map<UUID,List<String>> byRole=new HashMap<>();for(var x:mappings)byRole.computeIfAbsent(x.getRoleId(),k->new ArrayList<>()).add(pc.get(x.getPermissionId()));List<Map<String,Object>> assignable=allRoles.stream().filter(r->canAssign(p,r.getCode())).sorted(Comparator.comparingInt(r->-RANK.getOrDefault(r.getCode(),0))).map(r->Map.<String,Object>of("code",r.getCode(),"permissions",byRole.getOrDefault(r.getId(),List.of()).stream().sorted().toList())).toList();return Map.of("roles",assignable,"permissions",allPerms.stream().map(x->Map.of("code",x.getCode(),"description",x.getDescription(),"category",x.getCategory())).toList());}
 @Transactional public Set<String> permissionsFor(UUID tenantId,UUID userId){seed(tenantId);var ids=userRoles.findByUserId(userId).stream().map(UserRoleEntity::getRoleId).toList();if(ids.isEmpty())return Set.of();Map<UUID,String> codes=permissions.findByTenantIdOrderByCategoryAscCodeAsc(tenantId).stream().collect(Collectors.toMap(PermissionEntity::getId,PermissionEntity::getCode));return rolePermissions.findByRoleIdIn(ids).stream().map(x->codes.get(x.getPermissionId())).filter(Objects::nonNull).collect(Collectors.toUnmodifiableSet());}
 @Transactional(readOnly=true) public List<Map<String,Object>> staff(){var p=admin();Map<UUID,String> roleCode=roles.findByTenantId(p.tenantId()).stream().collect(Collectors.toMap(RoleEntity::getId,RoleEntity::getCode));List<Map<String,Object>> out=new ArrayList<>();for(var u:users.findByTenantIdOrderByNameAsc(p.tenantId())){var outletIds=userOutlets.findByUserId(u.getId()).stream().map(UserOutletEntity::getOutletId).toList();if(!p.hasRole("OWNER")&&!p.outletIds().isEmpty()&&Collections.disjoint(p.outletIds(),outletIds))continue;Map<String,Object> row=new LinkedHashMap<>();row.put("id",u.getId());row.put("name",u.getName());row.put("email",u.getEmail());row.put("employeeCode",u.getEmployeeCode()==null?"":u.getEmployeeCode());row.put("status",u.getStatus());row.put("version",u.getVersion());row.put("roles",userRoles.findByUserId(u.getId()).stream().map(x->roleCode.get(x.getRoleId())).filter(Objects::nonNull).toList());row.put("outletIds",outletIds);row.put("approvalLimits",limits(u.getId()));out.add(row);}return out;}
 @Transactional(readOnly=true) public List<Map<String,Object>> outlets(){var p=admin();List<Map<String,Object>> rows=jdbc.query("select id,name from outlets where tenant_id=? order by name",(rs,n)->Map.<String,Object>of("id",rs.getObject("id",UUID.class),"name",rs.getString("name")),p.tenantId());if(p.hasRole("OWNER")||p.outletIds().isEmpty())return rows;return rows.stream().filter(x->p.outletIds().contains(x.get("id"))).toList();}
 @Transactional public Map<String,Object> create(Map<String,Object> body){var p=admin();seed(p.tenantId());String name=required(body,"name",100);String email=required(body,"email",254).toLowerCase(Locale.ROOT);if(!EMAIL.matcher(email).matches())throw ApiException.bad("EMAIL","Invalid email");String employee=required(body,"employeeCode",32).toUpperCase(Locale.ROOT);if(!EMPLOYEE.matcher(employee).matches())throw ApiException.bad("EMPLOYEE_CODE","Use 3-32 uppercase letters, numbers, underscore, or dash");String password=required(body,"password",200);if(password.length()<10)throw ApiException.bad("PASSWORD","Password must contain at least 10 characters");String role=required(body,"role",40).toUpperCase(Locale.ROOT);if(!canAssign(p,role))throw ApiException.forbidden("ROLE_DELEGATION","You cannot assign this role");List<UUID> outletIds=uuids(body.get("outletIds"));if(outletIds.isEmpty())throw ApiException.bad("OUTLET_SCOPE","At least one outlet is required");for(UUID id:outletIds){Integer found=jdbc.queryForObject("select count(*) from outlets where id=? and tenant_id=?",Integer.class,id,p.tenantId());if(found==null||found==0)throw ApiException.notFound("OUTLET","Outlet not found");if(!p.hasRole("OWNER")&&!p.outletIds().contains(id))throw ApiException.forbidden("OUTLET_SCOPE","Cannot assign an outlet outside your scope");}var selected=roles.findByTenantId(p.tenantId()).stream().filter(x->x.getCode().equals(role)).findFirst().orElseThrow(()->ApiException.bad("ROLE","Unknown role"));UserEntity u=new UserEntity();u.setTenantId(p.tenantId());u.setName(name);u.setEmail(email);u.setEmployeeCode(employee);u.setPasswordHash(encoder.encode(password));try{users.saveAndFlush(u);}catch(DataIntegrityViolationException e){throw ApiException.conflict("USER_EXISTS","Email or employee code already exists");}UserRoleEntity ur=new UserRoleEntity();ur.setTenantId(p.tenantId());ur.setUserId(u.getId());ur.setRoleId(selected.getId());userRoles.save(ur);for(UUID id:new LinkedHashSet<>(outletIds)){UserOutletEntity uo=new UserOutletEntity();uo.setTenantId(p.tenantId());uo.setUserId(u.getId());uo.setOutletId(id);userOutlets.save(uo);}audit.write("USER_CREATED","USER",u.getId(),"role="+role+" outlets="+outletIds);return Map.of("id",u.getId(),"name",name,"email",email,"employeeCode",employee,"role",role,"outletIds",outletIds);}
 @Transactional public Map<String,Object> update(UUID userId,Map<String,Object> body,long expected){var p=admin();if(userId.equals(p.userId())&&(body.containsKey("role")||body.containsKey("status")||body.containsKey("outletIds")))throw ApiException.forbidden("SELF_ADMIN","You cannot change your own role, status, or scope");var u=users.findById(userId).orElseThrow(()->ApiException.notFound("USER","User not found"));if(!u.getTenantId().equals(p.tenantId()))throw ApiException.notFound("USER","User not found");if(u.getVersion()!=expected)throw ApiException.conflict("VERSION_CONFLICT","Staff account changed; reload before saving");String role=required(body,"role",40).toUpperCase(Locale.ROOT);if(!canAssign(p,role))throw ApiException.forbidden("ROLE_DELEGATION","You cannot assign this role");List<UUID> outletIds=uuids(body.get("outletIds"));if(outletIds.isEmpty())throw ApiException.bad("OUTLET_SCOPE","At least one outlet is required");for(UUID id:outletIds){if(!p.hasRole("OWNER")&&!p.outletIds().contains(id))throw ApiException.forbidden("OUTLET_SCOPE","Cannot assign an outlet outside your scope");Integer found=jdbc.queryForObject("select count(*) from outlets where id=? and tenant_id=?",Integer.class,id,p.tenantId());if(found==null||found==0)throw ApiException.notFound("OUTLET","Outlet not found");}String status=required(body,"status",20).toUpperCase(Locale.ROOT);if(!Set.of("ACTIVE","SUSPENDED","DISABLED").contains(status))throw ApiException.bad("USER_STATUS","Invalid status");if("OWNER".equals(currentRole(userId))&&(!"OWNER".equals(role)||!"ACTIVE".equals(status))&&activeOwners(p.tenantId())<=1)throw ApiException.conflict("LAST_OWNER","The final active owner cannot be removed or suspended");u.setName(required(body,"name",100));u.setStatus(status);users.saveAndFlush(u);var selected=roles.findByTenantId(p.tenantId()).stream().filter(x->x.getCode().equals(role)).findFirst().orElseThrow(()->ApiException.bad("ROLE","Unknown role"));userRoles.deleteAll(userRoles.findByUserId(userId));UserRoleEntity ur=new UserRoleEntity();ur.setTenantId(p.tenantId());ur.setUserId(userId);ur.setRoleId(selected.getId());userRoles.save(ur);userOutlets.deleteAll(userOutlets.findByUserId(userId));for(UUID id:new LinkedHashSet<>(outletIds)){UserOutletEntity uo=new UserOutletEntity();uo.setTenantId(p.tenantId());uo.setUserId(userId);uo.setOutletId(id);userOutlets.save(uo);}saveLimits(p,userId,body.get("approvalLimits"));jdbc.update("update refresh_tokens set revoked=true where user_id=?",userId);audit.write("USER_ACCESS_UPDATED","USER",userId,"role="+role+" status="+status+" outlets="+outletIds);return Map.of("id",userId,"version",u.getVersion(),"status",status,"role",role,"outletIds",outletIds);}
 private TenantPrincipal admin(){var p=TenantContext.require();if(!(p.hasRole("OWNER")||p.hasRole("MANAGER")))throw ApiException.forbidden("RBAC","Staff access management requires owner or manager role");return p;}
 private static boolean canAssign(TenantPrincipal p,String role){Integer target=RANK.get(role);if(target==null)return false;if(p.hasRole("OWNER"))return true;int own=p.roles().stream().mapToInt(x->RANK.getOrDefault(x,0)).max().orElse(0);return target<own&& !role.equals("OWNER");}
 private static String required(Map<String,Object>b,String k,int max){Object v=b.get(k);if(!(v instanceof String s)||s.isBlank())throw ApiException.bad("FIELD",k+" is required");s=s.strip();if(s.length()>max)throw ApiException.bad("FIELD",k+" is too long");return s;}
 private static List<UUID> uuids(Object raw){if(!(raw instanceof List<?> list))throw ApiException.bad("OUTLET_SCOPE","outletIds must be an array");try{return list.stream().map(String::valueOf).map(UUID::fromString).toList();}catch(Exception e){throw ApiException.bad("OUTLET_SCOPE","Invalid outlet ID");}}
 private String currentRole(UUID userId){Map<UUID,String> map=roles.findByTenantId(TenantContext.require().tenantId()).stream().collect(Collectors.toMap(RoleEntity::getId,RoleEntity::getCode));return userRoles.findByUserId(userId).stream().map(x->map.get(x.getRoleId())).filter(Objects::nonNull).findFirst().orElse("");}
 private int activeOwners(UUID tenant){return Optional.ofNullable(jdbc.queryForObject("select count(*) from users u join user_roles ur on ur.user_id=u.id join roles r on r.id=ur.role_id where u.tenant_id=? and u.status='ACTIVE' and r.code='OWNER'",Integer.class,tenant)).orElse(0);}
 private Map<String,Object> limits(UUID userId){List<Map<String,Object>> rows=jdbc.query("select discount_bps,refund_paise,void_paise,stock_adjustment_paise from user_approval_limits where user_id=?",(rs,n)->Map.of("discountBps",rs.getInt(1),"refundPaise",rs.getLong(2),"voidPaise",rs.getLong(3),"stockAdjustmentPaise",rs.getLong(4)),userId);return rows.isEmpty()?Map.of("discountBps",0,"refundPaise",0,"voidPaise",0,"stockAdjustmentPaise",0):rows.getFirst();}
 private void saveLimits(TenantPrincipal p,UUID userId,Object raw){if(!(raw instanceof Map<?,?> m))return;int discount=number(m.get("discountBps"),0,10000,"discountBps").intValue();long refund=number(m.get("refundPaise"),0,100_000_000,"refundPaise").longValue();long voidLimit=number(m.get("voidPaise"),0,100_000_000,"voidPaise").longValue();long stock=number(m.get("stockAdjustmentPaise"),0,100_000_000,"stockAdjustmentPaise").longValue();jdbc.update("insert into user_approval_limits(tenant_id,user_id,discount_bps,refund_paise,void_paise,stock_adjustment_paise,updated_by) values(?,?,?,?,?,?,?) on conflict(user_id) do update set discount_bps=excluded.discount_bps,refund_paise=excluded.refund_paise,void_paise=excluded.void_paise,stock_adjustment_paise=excluded.stock_adjustment_paise,updated_at=now(),updated_by=excluded.updated_by",p.tenantId(),userId,discount,refund,voidLimit,stock,p.userId());}
 private static Number number(Object raw,long min,long max,String field){if(!(raw instanceof Number n)||n.longValue()<min||n.longValue()>max)throw ApiException.bad("APPROVAL_LIMIT",field+" is outside the allowed range");return n;}
 private void seed(UUID tenant){Integer existing=jdbc.queryForObject("select count(*) from roles where tenant_id=?",Integer.class,tenant);if(existing!=null&&existing>=RANK.size())return;for(String role:RANK.keySet())jdbc.update("insert into roles(id,tenant_id,code) values (gen_random_uuid(),?,?) on conflict(tenant_id,code) do nothing",tenant,role);for(String[] x:PERMISSION_META)jdbc.update("insert into permissions(id,tenant_id,code,description,category) values(gen_random_uuid(),?,?,?,?) on conflict(tenant_id,code) do nothing",tenant,x[0],x[1],x[2]);var ps=permissions.findByTenantIdOrderByCategoryAscCodeAsc(tenant);Map<String,UUID> ids=ps.stream().collect(Collectors.toMap(PermissionEntity::getCode,PermissionEntity::getId));var rs=roles.findByTenantId(tenant);for(var role:rs){Collection<String> wanted=role.getCode().equals("OWNER")?ids.keySet():Arrays.asList(ROLE_PERMISSIONS.getOrDefault(role.getCode(),new String[0]));for(String code:wanted){UUID pid=ids.get(code);if(pid!=null)jdbc.update("insert into role_permissions(tenant_id,role_id,permission_id) values (?,?,?) on conflict do nothing",tenant,role.getId(),pid);}}}
}
