package com.restaurant.platform.infrastructure;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

class DelegatingConnection implements Connection {
	private final Connection d;
	DelegatingConnection(Connection d) { this.d = d; }
	Connection getDelegate() { return d; }
	@Override public Statement createStatement() throws SQLException { return d.createStatement(); }
	@Override public PreparedStatement prepareStatement(String sql) throws SQLException { return d.prepareStatement(sql); }
	@Override public CallableStatement prepareCall(String sql) throws SQLException { return d.prepareCall(sql); }
	@Override public String nativeSQL(String sql) throws SQLException { return d.nativeSQL(sql); }
	@Override public void setAutoCommit(boolean autoCommit) throws SQLException { d.setAutoCommit(autoCommit); }
	@Override public boolean getAutoCommit() throws SQLException { return d.getAutoCommit(); }
	@Override public void commit() throws SQLException { d.commit(); }
	@Override public void rollback() throws SQLException { d.rollback(); }
	@Override public void close() throws SQLException { d.close(); }
	@Override public boolean isClosed() throws SQLException { return d.isClosed(); }
	@Override public DatabaseMetaData getMetaData() throws SQLException { return d.getMetaData(); }
	@Override public void setReadOnly(boolean readOnly) throws SQLException { d.setReadOnly(readOnly); }
	@Override public boolean isReadOnly() throws SQLException { return d.isReadOnly(); }
	@Override public void setCatalog(String catalog) throws SQLException { d.setCatalog(catalog); }
	@Override public String getCatalog() throws SQLException { return d.getCatalog(); }
	@Override public void setTransactionIsolation(int level) throws SQLException { d.setTransactionIsolation(level); }
	@Override public int getTransactionIsolation() throws SQLException { return d.getTransactionIsolation(); }
	@Override public SQLWarning getWarnings() throws SQLException { return d.getWarnings(); }
	@Override public void clearWarnings() throws SQLException { d.clearWarnings(); }
	@Override public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException { return d.createStatement(resultSetType, resultSetConcurrency); }
	@Override public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException { return d.prepareStatement(sql, resultSetType, resultSetConcurrency); }
	@Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException { return d.prepareCall(sql, resultSetType, resultSetConcurrency); }
	@Override public Map<String, Class<?>> getTypeMap() throws SQLException { return d.getTypeMap(); }
	@Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException { d.setTypeMap(map); }
	@Override public void setHoldability(int holdability) throws SQLException { d.setHoldability(holdability); }
	@Override public int getHoldability() throws SQLException { return d.getHoldability(); }
	@Override public Savepoint setSavepoint() throws SQLException { return d.setSavepoint(); }
	@Override public Savepoint setSavepoint(String name) throws SQLException { return d.setSavepoint(name); }
	@Override public void rollback(Savepoint savepoint) throws SQLException { d.rollback(savepoint); }
	@Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { d.releaseSavepoint(savepoint); }
	@Override public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { return d.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability); }
	@Override public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { return d.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability); }
	@Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { return d.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability); }
	@Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException { return d.prepareStatement(sql, autoGeneratedKeys); }
	@Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException { return d.prepareStatement(sql, columnIndexes); }
	@Override public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException { return d.prepareStatement(sql, columnNames); }
	@Override public Clob createClob() throws SQLException { return d.createClob(); }
	@Override public Blob createBlob() throws SQLException { return d.createBlob(); }
	@Override public NClob createNClob() throws SQLException { return d.createNClob(); }
	@Override public SQLXML createSQLXML() throws SQLException { return d.createSQLXML(); }
	@Override public boolean isValid(int timeout) throws SQLException { return d.isValid(timeout); }
	@Override public void setClientInfo(String name, String value) throws SQLClientInfoException { d.setClientInfo(name, value); }
	@Override public void setClientInfo(Properties properties) throws SQLClientInfoException { d.setClientInfo(properties); }
	@Override public String getClientInfo(String name) throws SQLException { return d.getClientInfo(name); }
	@Override public Properties getClientInfo() throws SQLException { return d.getClientInfo(); }
	@Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { return d.createArrayOf(typeName, elements); }
	@Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { return d.createStruct(typeName, attributes); }
	@Override public void setSchema(String schema) throws SQLException { d.setSchema(schema); }
	@Override public String getSchema() throws SQLException { return d.getSchema(); }
	@Override public void abort(Executor executor) throws SQLException { d.abort(executor); }
	@Override public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException { d.setNetworkTimeout(executor, milliseconds); }
	@Override public int getNetworkTimeout() throws SQLException { return d.getNetworkTimeout(); }
	@Override public <T> T unwrap(Class<T> iface) throws SQLException { return d.unwrap(iface); }
	@Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return d.isWrapperFor(iface); }
}
