package com.restaurant.platform.infrastructure;

import com.restaurant.platform.api.TenantContext;
import com.restaurant.platform.api.TenantPrincipal;
import com.zaxxer.hikari.HikariDataSource;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.DelegatingDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

@Configuration
public class RlsDataSourceConfig {

	@Bean
	static BeanPostProcessor rlsWrap() {
		return new BeanPostProcessor() {
			@Override
			public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
				if (bean instanceof HikariDataSource hikari && !beanName.toLowerCase().contains("flyway")) {
					return new DelegatingDataSource(hikari) {
						@Override
						public Connection getConnection() throws SQLException {
							return new TenantConnection(super.getConnection());
						}

						@Override
						public Connection getConnection(String username, String password) throws SQLException {
							return new TenantConnection(super.getConnection(username, password));
						}
					};
				}
				return bean;
			}
		};
	}

	static final class TenantConnection extends DelegatingConnection {
		private String appliedKey;

		TenantConnection(Connection delegate) { super(delegate); }

		@Override
		public Statement createStatement() throws SQLException {
			applyTenant();
			return super.createStatement();
		}

		@Override
		public java.sql.PreparedStatement prepareStatement(String sql) throws SQLException {
			applyTenant();
			return super.prepareStatement(sql);
		}

		@Override
		public java.sql.PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
			applyTenant();
			return super.prepareStatement(sql, autoGeneratedKeys);
		}

		@Override
		public java.sql.PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
			applyTenant();
			return super.prepareStatement(sql, resultSetType, resultSetConcurrency);
		}

		@Override
		public java.sql.PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
			applyTenant();
			return super.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
		}

		@Override
		public void close() throws SQLException {
			try (Statement st = getDelegate().createStatement()) {
				st.execute("SELECT set_config('app.current_tenant', '', false), set_config('app.bootstrap', 'off', false)");
			} catch (SQLException ignored) {
				// closing anyway
			}
			appliedKey = null;
			super.close();
		}

		@Override
		public void setAutoCommit(boolean autoCommit) throws SQLException {
			super.setAutoCommit(autoCommit);
			applyTenant();
		}

		private void applyTenant() throws SQLException {
			TenantPrincipal p = TenantContext.get();
			String tenant = (p != null && p.tenantId() != null) ? p.tenantId().toString() : "";
			String boot = TenantContext.bootstrap() ? "on" : "off";
			String key = boot + "|" + tenant;
			if (key.equals(appliedKey)) {
				return;
			}
			try (Statement st = getDelegate().createStatement()) {
				st.execute("SELECT set_config('app.bootstrap', '" + boot + "', false), set_config('app.current_tenant', '" + tenant + "', false)");
			}
			appliedKey = key;
		}
	}
}
