package com.restaurant.platform.application;

import com.restaurant.identity.application.JwtService;
import com.restaurant.platform.api.ApiException;
import com.restaurant.platform.api.AppProperties;
import com.restaurant.platform.api.IdempotencyService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;

@Service
public class PlatformAuthService {
 private final JdbcTemplate jdbc; private final PasswordEncoder encoder; private final JwtService jwt; private final AppProperties properties;
 public PlatformAuthService(JdbcTemplate j,PasswordEncoder e,JwtService jwt,AppProperties p){jdbc=j;encoder=e;this.jwt=jwt;properties=p;}
 @Transactional public Map<String,Object> login(String username,String password){if(username==null||password==null)throw ApiException.unauthorized("Bad credentials");var a=jdbc.query("select id,email,password_hash,display_name,status from platform_administrators where lower(email)=?",(r,n)->new Admin(UUID.fromString(r.getString("id")),r.getString("email"),r.getString("password_hash"),r.getString("display_name"),r.getString("status")),username.trim().toLowerCase(Locale.ROOT));if(a.isEmpty()||a.getFirst().hash()==null||!encoder.matches(password,a.getFirst().hash()))throw ApiException.unauthorized("Bad credentials");if(!"ACTIVE".equals(a.getFirst().status()))throw ApiException.unauthorized("Account is not active");jdbc.update("update platform_administrators set last_login_at=now(),updated_at=now() where id=?",a.getFirst().id());return issue(a.getFirst());}
 @Transactional public Map<String,Object> refresh(String raw){if(raw==null)throw ApiException.unauthorized("Invalid refresh");var x=jdbc.query("select r.id,r.administrator_id,r.expires_at,r.revoked,a.email,a.password_hash,a.display_name,a.status from platform_refresh_tokens r join platform_administrators a on a.id=r.administrator_id where r.token_hash=? for update",(r,n)->new Refresh(UUID.fromString(r.getString("id")),new Admin(UUID.fromString(r.getString("administrator_id")),r.getString("email"),r.getString("password_hash"),r.getString("display_name"),r.getString("status")),r.getTimestamp("expires_at").toInstant(),r.getBoolean("revoked")),IdempotencyService.sha256(raw));if(x.isEmpty()||x.getFirst().revoked()||x.getFirst().expires().isBefore(Instant.now())||!"ACTIVE".equals(x.getFirst().admin().status()))throw ApiException.unauthorized("Invalid refresh");jdbc.update("update platform_refresh_tokens set revoked=true where id=?",x.getFirst().id());return issue(x.getFirst().admin());}
 @Transactional public void logout(String raw){if(raw!=null)jdbc.update("update platform_refresh_tokens set revoked=true where token_hash=?",IdempotencyService.sha256(raw));}
 @Transactional public boolean bootstrap(String email,String password,String name){Integer count=jdbc.queryForObject("select count(*) from platform_administrators",Integer.class);if(count!=null&&count>0)return false;if(email==null||email.isBlank()||password==null||password.length()<14)throw new IllegalArgumentException("Platform bootstrap requires an email and a password of at least 14 characters");jdbc.update("insert into platform_administrators(email,password_hash,display_name) values (?,?,?)",email.trim().toLowerCase(Locale.ROOT),encoder.encode(password),name==null||name.isBlank()?"Platform Administrator":name.trim());return true;}

 @Transactional(readOnly=true) public List<Map<String,Object>> administrators(){return jdbc.query("select id,email,display_name,status,created_at,last_login_at from platform_administrators order by created_at",(r,n)->{Map<String,Object> row=new LinkedHashMap<>();row.put("id",r.getString("id"));row.put("email",r.getString("email"));row.put("displayName",r.getString("display_name"));row.put("status",r.getString("status"));row.put("createdAt",r.getTimestamp("created_at").toInstant().toString());row.put("lastLoginAt",r.getTimestamp("last_login_at")==null?null:r.getTimestamp("last_login_at").toInstant().toString());return row;});}

 @Transactional public Map<String,Object> invite(UUID actorId,String email,String name){String normalized=email==null?"":email.trim().toLowerCase(Locale.ROOT);if(!normalized.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))throw ApiException.bad("EMAIL","Enter a valid email address");String token=jwt.refreshToken();Instant expires=Instant.now().plus(48,ChronoUnit.HOURS);try{UUID id=jdbc.queryForObject("insert into platform_administrators(email,password_hash,display_name,status,setup_token_hash,setup_expires_at) values (?,null,?,'INVITED',?,?) returning id",UUID.class,normalized,name==null||name.isBlank()?"Platform Administrator":name.trim(),IdempotencyService.sha256(token),Timestamp.from(expires));audit(actorId,id,"ADMINISTRATOR_INVITED",normalized);return Map.of("id",id.toString(),"setupToken",token,"setupExpiresAt",expires.toString());}catch(org.springframework.dao.DataIntegrityViolationException e){throw ApiException.conflict("ADMINISTRATOR_EXISTS","A platform administrator with this email already exists");}}

 @Transactional public void setupPassword(String token,String password){if(token==null||password==null||password.length()<14)throw ApiException.bad("PASSWORD","Password must contain at least 14 characters");var ids=jdbc.query("select id from platform_administrators where setup_token_hash=? and setup_expires_at>now() and status='INVITED' for update",(r,n)->UUID.fromString(r.getString("id")),IdempotencyService.sha256(token));if(ids.isEmpty())throw ApiException.bad("SETUP_INVALID","This setup link is invalid or expired");jdbc.update("update platform_administrators set password_hash=?,status='ACTIVE',setup_token_hash=null,setup_expires_at=null,updated_at=now() where id=?",encoder.encode(password),ids.getFirst());audit(ids.getFirst(),ids.getFirst(),"ADMINISTRATOR_ACTIVATED","Password setup completed");}

 @Transactional public void changeStatus(UUID actorId,UUID administratorId,String status){if(!List.of("ACTIVE","DISABLED").contains(status))throw ApiException.bad("STATUS","Invalid administrator status");if(actorId.equals(administratorId)&&"DISABLED".equals(status))throw ApiException.bad("SELF_DISABLE","You cannot disable your own account");Integer found=jdbc.queryForObject("select count(*) from platform_administrators where id=?",Integer.class,administratorId);if(found==null||found==0)throw ApiException.notFound("ADMINISTRATOR","Platform administrator not found");jdbc.update("update platform_administrators set status=?,updated_at=now() where id=?",status,administratorId);if("DISABLED".equals(status))jdbc.update("update platform_refresh_tokens set revoked=true where administrator_id=?",administratorId);audit(actorId,administratorId,"ADMINISTRATOR_"+status,null);}

 private void audit(UUID actorId,UUID administratorId,String action,String detail){jdbc.update("insert into platform_administrator_audit(actor_id,administrator_id,action,detail) values (?,?,?,?)",actorId,administratorId,action,detail);}
 private Map<String,Object> issue(Admin a){String r=jwt.refreshToken();jdbc.update("insert into platform_refresh_tokens(administrator_id,token_hash,expires_at) values (?,?,?)",a.id(),IdempotencyService.sha256(r),java.sql.Timestamp.from(Instant.now().plusSeconds(properties.getJwt().getRefreshTtlSeconds())));return Map.of("accessToken",jwt.platformToken(a.id()),"refreshToken",r,"userId",a.id().toString(),"displayName",a.name(),"roles",List.of("SUPER_ADMIN"));}
 private record Admin(UUID id,String email,String hash,String name,String status){} private record Refresh(UUID id,Admin admin,Instant expires,boolean revoked){}
}
